# Generated by Django 2.2 on 2019-05-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190502_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='social',
            field=models.CharField(max_length=255, null=True, verbose_name='Social Media'),
        ),
    ]
