# Generated by Django 2.2 on 2019-05-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190505_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='social',
            field=models.CharField(blank=True, default='Facebook, Twitter, etc', max_length=255, verbose_name='Social Media'),
        ),
    ]
