# Generated by Django 2.2 on 2019-05-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190505_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Social Media'),
        ),
    ]
