# Generated by Django 2.2 on 2019-05-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190505_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='social',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
