# Generated by Django 2.2 on 2020-05-12 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190506_0710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': '  Countries'},
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Event title:')),
                ('content', models.CharField(default='', max_length=100, verbose_name='Content:')),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Link:')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
