# Generated by Django 2.2 on 2020-05-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_calendar_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Event title:'),
        ),
    ]
